#!/usr/bin/env bash
set -o xtrace

IMAGE="localhost:5000/bitnami/kubectl"
TAG=$1
DIGEST=$2
OUTDIR="$PWD/src"

skopeo copy --src-tls-verify=false --format=oci --multi-arch=all --dest-oci-accept-uncompressed-layers "docker://$IMAGE@$DIGEST" "oci:$OUTDIR:$TAG"
git status $OUTDIR
